# Generated by Django 5.2.7 on 2025-10-11 23:26

import closet.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.ImageField(blank=True, null=True, upload_to=closet.models.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'closet_images',
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('height', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('box_x', models.FloatField(default=0)),
                ('box_y', models.FloatField(default=0)),
                ('box_w', models.FloatField(default=0)),
                ('box_h', models.FloatField(default=0)),
                ('path', models.ImageField(blank=True, null=True, upload_to=closet.models.item_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='image', to='closet.imagemodel')),
            ],
            options={
                'db_table': 'closet_items',
            },
        ),
    ]
