# Generated by Django 5.2.7 on 2025-10-11 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('result_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tryon', related_query_name='recommendation', to='recommendation.recommendationmodel')),
            ],
            options={
                'db_table': 'tryons',
            },
        ),
    ]
