# Generated by Django 5.2.7 on 2025-10-13 08:45

import tryon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tryonmodel',
            old_name='photo_file_name',
            new_name='photo_mime_type',
        ),
        migrations.RemoveField(
            model_name='tryonmodel',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='tryonmodel',
            name='result_url',
        ),
        migrations.AddField(
            model_name='tryonmodel',
            name='photo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tryonmodel',
            name='result_path',
            field=models.ImageField(blank=True, null=True, upload_to=tryon.models.tryon_result_upload_path),
        ),
        migrations.AlterField(
            model_name='tryonmodel',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to=tryon.models.tryon_photo_upload_path),
        ),
    ]
