# Generated by Django 5.2.7 on 2025-10-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='url',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
