# Generated by Django 5.2.7 on 2025-10-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='path',
            field=models.FilePathField(blank=True, null=True, path='/home/naeem-md93/Projects/NFL-server/media'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='closet/images/'),
        ),
    ]
