# Generated by Django 5.2.7 on 2025-10-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet_image', '0002_imagemodel_path_alter_imagemodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='path',
        ),
    ]
