# Generated by Django 5.2.7 on 2025-10-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_image', '0003_remove_imagemodel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
