# Generated by Django 5.2.7 on 2025-10-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet_image', '0004_alter_imagemodel_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='url',
            new_name='path',
        ),
    ]
