# Generated by Django 5.2.7 on 2025-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_image', '0005_rename_url_imagemodel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
