# Generated by Django 5.2.7 on 2025-10-09 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet_item', '0004_itemmodel_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(related_name='recommendations', to='closet_item.itemmodel')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
    ]
