# Generated by Django 5.2.7 on 2025-10-06 23:34

import closet_item.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('brx', models.FloatField(default=0)),
                ('bry', models.FloatField(default=0)),
                ('brw', models.FloatField(default=0)),
                ('brh', models.FloatField(default=0)),
                ('bax', models.PositiveIntegerField(default=0)),
                ('bay', models.PositiveIntegerField(default=0)),
                ('baw', models.PositiveIntegerField(default=0)),
                ('bah', models.PositiveIntegerField(default=0)),
                ('url', models.ImageField(blank=True, null=True, upload_to=closet_item.models.item_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='image', to='closet_image.imagemodel')),
            ],
            options={
                'db_table': 'closet_items',
            },
        ),
    ]
