# Generated by Django 5.2.7 on 2025-10-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='closet/items/'),
        ),
    ]
