# Generated by Django 5.2.7 on 2025-10-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_item', '0002_alter_itemmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
