# Generated by Django 5.2.7 on 2025-10-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_item', '0003_itemmodel_path_alter_itemmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
